// Code generated by templ DO NOT EDIT.

package moxy

import "github.com/a-h/templ"
import "context"
import "io"
import "github.com/joe-davidson1802/turbo-templ/turbo"

func HomeTemplate() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		_, err = io.WriteString(w, "<html>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<head>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<title>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, templ.EscapeString("Moxy - Admin Portal"))
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</title>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<script")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " type=\"module\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, ">")
		if err != nil {
			return err
		}
		err = Raw("import hotwiredTurbo from 'https://cdn.skypack.dev/@hotwired/turbo';").Render(ctx, w)
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</script>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<link")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " rel=\"stylesheet\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " href=\"https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " integrity=\"sha512-EZLkOqwILORob+p0BXZc+Vm3RgJBOe1Iq/0fiI7r/wJgzOFZMlsqTa29UEl6v6U6gsV4uIpsNZoV32YZqrCRCQ==\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " crossorigin=\"anonymous\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " referrerpolicy=\"no-referrer\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "/>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</head>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<body>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<div")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " class=\"container\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, ">")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<section")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " class=\"header\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, ">")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<h1")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " class=\"title\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, ">")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, templ.EscapeString("Moxy"))
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</h1>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</section>")
		if err != nil {
			return err
		}
		err = turbo.TurboFrame(turbo.TurboFrameOptions{Id: "moxy-config", Src: "/moxy/config"}).Render(ctx, w)
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</div>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</body>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</html>")
		if err != nil {
			return err
		}
		return err
	})
}

