// Code generated by templ DO NOT EDIT.

package moxy

import "github.com/a-h/templ"
import "context"
import "io"
import "strconv"
import "github.com/joe-davidson1802/moxy/config"
import "github.com/joe-davidson1802/moxy/types"

func MoveTemplate(c *config.Config, id int, dir types.MoveDirection, text string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		_, err = io.WriteString(w, "<form")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " action=")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, templ.EscapeString(c.MoxyPath + "/move"))
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " method=\"POST\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " target=\"table\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, ">")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<input")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " name=\"id\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " value=")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, templ.EscapeString(strconv.Itoa(id)))
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " size=\"50\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " hidden=\"true\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "/>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<input")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " name=\"direction\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " value=")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, templ.EscapeString(dir.String()))
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " size=\"50\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " hidden=\"true\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "/>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<button")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " type=\"submit\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, ">")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, templ.EscapeString(text))
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</button>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</form>")
		if err != nil {
			return err
		}
		return err
	})
}

func DeleteTemplate(c *config.Config, id int) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		_, err = io.WriteString(w, "<form")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " action=")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, templ.EscapeString(c.MoxyPath + "/delete"))
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " method=\"POST\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " target=\"table\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, ">")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<input")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " name=\"id\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " value=")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, templ.EscapeString(strconv.Itoa(id)))
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " size=\"50\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " hidden=\"true\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "/>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<button")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " type=\"submit\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, ">")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, templ.EscapeString("Delete"))
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</button>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</form>")
		if err != nil {
			return err
		}
		return err
	})
}

func UpstreamTableTemplate(c *config.Config) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		_, err = io.WriteString(w, "<table>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<tr>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<th>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, templ.EscapeString("Priority"))
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</th>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<th>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, templ.EscapeString("Path Prefix"))
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</th>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<th>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, templ.EscapeString("Destination"))
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</th>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<th>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, templ.EscapeString("Move"))
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</th>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<th>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, templ.EscapeString("Delete"))
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</th>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</tr>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<tr>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<td>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, templ.EscapeString("Default"))
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</td>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<td>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, templ.EscapeString("/"))
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</td>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<td>")
		if err != nil {
			return err
		}
		err = UpstreamUrlTemplate(c, "default", c.DefaultUpstream).Render(ctx, w)
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</td>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</tr>")
		if err != nil {
			return err
		}
		for i, up := range c.Upstreams {
			_, err = io.WriteString(w, "<tr>")
			if err != nil {
				return err
			}
			_, err = io.WriteString(w, "<td>")
			if err != nil {
				return err
			}
			_, err = io.WriteString(w, templ.EscapeString(strconv.Itoa(i)))
			if err != nil {
				return err
			}
			_, err = io.WriteString(w, "</td>")
			if err != nil {
				return err
			}
			_, err = io.WriteString(w, "<td>")
			if err != nil {
				return err
			}
			err = UpstreamPathPrefixTemplate(c, strconv.Itoa(i), up.PathPrefix).Render(ctx, w)
			if err != nil {
				return err
			}
			_, err = io.WriteString(w, "</td>")
			if err != nil {
				return err
			}
			_, err = io.WriteString(w, "<td>")
			if err != nil {
				return err
			}
			err = UpstreamUrlTemplate(c, strconv.Itoa(i), up.Url).Render(ctx, w)
			if err != nil {
				return err
			}
			_, err = io.WriteString(w, "</td>")
			if err != nil {
				return err
			}
			_, err = io.WriteString(w, "<td>")
			if err != nil {
				return err
			}
			err = MoveTemplate(c, i, types.DirectionUp, "Up").Render(ctx, w)
			if err != nil {
				return err
			}
			err = MoveTemplate(c, i, types.DirectionDown, "Down").Render(ctx, w)
			if err != nil {
				return err
			}
			_, err = io.WriteString(w, "</td>")
			if err != nil {
				return err
			}
			_, err = io.WriteString(w, "<td>")
			if err != nil {
				return err
			}
			err = DeleteTemplate(c, i).Render(ctx, w)
			if err != nil {
				return err
			}
			_, err = io.WriteString(w, "</td>")
			if err != nil {
				return err
			}
			_, err = io.WriteString(w, "</tr>")
			if err != nil {
				return err
			}
		}
		_, err = io.WriteString(w, "</table>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<h2>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, templ.EscapeString("New Upstream"))
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</h2>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<form")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " action=")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, templ.EscapeString(c.MoxyPath + "/config"))
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " method=\"POST\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " target=\"table\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, ">")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<label>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, templ.EscapeString("Path Prefix "))
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<input")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " name=\"pathprefix\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " size=\"50\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "/>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</label>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<label>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, templ.EscapeString("Url "))
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<input")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " name=\"url\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " size=\"50\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "/>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</label>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<button")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " type=\"submit\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, ">")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, templ.EscapeString("Add"))
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</button>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</form>")
		if err != nil {
			return err
		}
		return err
	})
}

